<?php require __DIR__ . '/../navbar.phtml' ?>

<?php $errors = $_SESSION['errors'] ?? [];
unset($_SESSION['errors']);

?>

<div class="text-center mb-5">
    <h1 class="fs-2 title">Editar Funcionário</h1>
    <div class="container page-create">

        <form method="POST" action="<?= route('workers.update', ['id' => $worker->id]) ?>" class="mb-4">
            <input type="hidden" name="_method" value="PUT">
            <div class="mb-3 row">
                <div class="col-12 col-sm-6">
                    <label for="name" class="form-label">Nome</label>
                    <input type="text" name="worker[name]" id="name" class="form-control" placeholder="Digite o nome" value="<?= $worker->name ?>">
                    <?php if (array_key_exists('name', $errors)): ?>
                        <div class="text-danger"><?= $errors['name'] ?></div>
                    <?php endif; ?>
                </div>
                <div class="col-12 col-sm-3">
                    <label for="cpf" class="form-label">CPF</label>
                    <input type="text" name="cpf" id="cpf" class="form-control" placeholder="Digite o CPF" value="<?= $worker->cpf ?>" disabled>
                </div>
                <div class="col-12 col-sm-3">
                    <label for="sex" class="form-label">Sexo</label>
                    <select name="worker[sex]" class="form-control" id="sex">
                        <option value="">Selecione</option>
                        <option value="male" <?= $worker->sex == 'male' ? 'selected' : '' ?>>Masculino</option>
                        <option value="female" <?= $worker->sex == 'female' ? 'selected' : '' ?>>Feminino</option>
                    </select>
                    <?php if (array_key_exists('sex', $errors)): ?>
                        <div class="text-danger"><?= $errors['sex'] ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-12 col-sm-9">
                    <label for="address" class="form-label">Endereço</label>
                    <input type="text" name="worker[address]" id="address" class="form-control" placeholder="Digite o endereço" value="<?= $worker->address ?>">
                    <?php if (array_key_exists('address', $errors)): ?>
                        <div class="text-danger"><?= $errors['address'] ?></div>
                    <?php endif; ?>
                </div>
                <div class="col-12 col-sm-3">
                    <label for="daily_hours" class="form-label">Carga horária</label>
                    <input type="number" name="worker[daily_hours]" id="daily_hours" class="form-control" placeholder="Digite a carga horária" min="4" max="10" value="<?= $worker->daily_hours ?>">
                    <?php if (array_key_exists('daily_hours', $errors)): ?>
                        <div class="text-danger"><?= $errors['daily_hours'] ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-12 col-sm-6">
                    <label for="position_id" class="form-label">Cargo</label>
                    <select name="worker[position_id]" class="form-control" id="position_id">
                        <option value="">Selecione</option>
                        <?php foreach($positions as $position) : ?>
                            <option
                                value="<?= $position->id ?>"
                                <?= ($worker->position_id == $position->id) ? 'selected' : '' ?>
                            >
                                <?= $position->name ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <?php if (array_key_exists('position_id', $errors)): ?>
                        <div class="text-danger"><?= $errors['position_id'] ?></div>
                    <?php endif; ?>
                </div>
                <div class="col-12 col-sm-6">
                    <label for="phone" class="form-label">Telefone</label>
                    <input type="text" name="worker[phone]" id="phone" class="form-control" placeholder="Digite o telefone" value="<?= $worker->phone ?>">
                    <?php if (array_key_exists('phone', $errors)): ?>
                        <div class="text-danger"><?= $errors['phone'] ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="mb-3 row">
                <div class="col-12 col-sm-6">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" name="email" id="email" class="form-control" placeholder="Digite o email" value="<?= $worker->email ?>" disabled>
                </div>
                <div class="col-12 col-sm-6">
                    <label for="password" class="form-label">Senha</label>
                    <input type="text" name="worker[password]" id="password" class="form-control" placeholder="Digite a senha" value="<?= $worker->password ?>">
                    <?php if (array_key_exists('password', $errors)): ?>
                        <div class="text-danger"><?= $errors['password'] ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>
