<?php require __DIR__ . '/../navbar.phtml' ?>

<h1 class="text-center fs-2 title">Gerenciar Cargos</h1>


<div class="container">
    <div class="mb-2 button-back">
        <a href="<?= route("admins.workers") ?>" class="fs-5 back"><i class="bi bi-arrow-left"></i>Voltar</a>
    </div>

    <a class="btn btn-success mb-2" href="<?= route("positions.create") ?>">Criar</a>

    <h2 class="mb-3">Lista de cargos</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($positions as $position) : ?>
                <tr>
                    <td><?= $position->name ?></td>
                    <td>
                        <div class="d-flex flex-row">
                            <a href="<?= route('admins.edit', ['id' => $position->id]) ?>" class='btn btn-warning btn-sm mx-2'>
                                <i class='bi bi-pencil-square'></i> Editar
                            </a>
                            <form action="<?= route('admins.destroy', ['id' => $position->id]) ?>" method="POST" class="m-0">
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class='btn btn-danger btn-sm'>
                                    <i class='bi bi-trash'></i> Excluir
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="pagination">
        <a href="#">Anterior</a>
        <a href="#" class="active">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#">Próximo</a>
    </div>
</div>
