<form class="form-login" action="/login" method="POST">
  <span class="display-1">HiBye</span>
  <h1 class="h3 mb-3 font-weight-normal">Login</h1>
  <label for="inputEmail" class="sr-only">Email</label>
  <input type="email" id="inputEmail" name="user[email]" class="form-control" placeholder="Email" required="" autofocus="">
  <label for="inputPassword" class="sr-only">Senha</label>
  <input type="password" id="inputPassword" name="user[password]" class="form-control" placeholder="Senha" required="">
  <button class="btn btn-lg text-white" type="submit">Entrar</button>
</form>
