<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Usuários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Cartão ponto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= route('admins.admins') ?>">Administradores</a>
                </li>
            </ul>
            <div class="ms-auto">
                <a class="nav-link" href="<?= route('admins.logout') ?>">Sair</a>
            </div>
        </div>
    </div>
</nav>
