<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?= route('admins.root') ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= route('workers.workers') ?>">Funcionários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Cartão ponto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= route('admins.admins') ?>">Administradores</a>
                </li>
            </ul>
            <div class="ms-auto">
                <div class="dropdown">
                    <button class="btn-dropdown dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="<?= currentAdmin()->profileImage()->path() ?>" alt="profileImage" class="profileImage">
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item"><?= currentAdmin()->email ?></a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="<?= route('admins.logout') ?>">Sair</a>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</nav>