<?php require __DIR__ . '/../navbar.phtml' ?>
<?php $errors = $_SESSION['errors'] ?? [];
unset($_SESSION['errors']);
$image_error = $_SESSION['image_error'] ?? '';
unset($_SESSION['image_error']);
?>

<div class="text-center">
    <h1 class="fs-2 title">Editar Administrador</h1>
    <div class="container page-create">

        <form method="POST" action="<?= route('admins.update', ['id' => $admin->id]) ?>" enctype="multipart/form-data" class="mb-4">
            <input type="hidden" name="_method" value="PUT">
            <img src="<?= $admin->profileImage()->path() ?>" alt="Imagem de Perfil" class="profileImage mb-3">
            <div class="mb-3 col-12 col-sm-6 offset-sm-3">
                <label for="email" class="form-label">Email</label>
                <input type="text" name="email" id="email" class="form-control" placeholder="Digite o email" value="<?= $admin->email ?>" disabled>
            </div>
            <div class="mb-3 col-12 col-sm-6 offset-sm-3">
                <label for="password" class="form-label">Nova Senha</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Senha">
                <?php if (array_key_exists('password', $errors)): ?>
                    <div class="text-danger"><?= $errors['password'] ?></div>
                <?php endif; ?>
            </div>
            <div class="mb-3 col-12 col-sm-6 offset-sm-3">
                <label for="profile_image" class="form-label">Imagem de Perfil</label>
                <input type="file" name="profile_image" id="profile_image" class="form-control">
                <?php if (!empty($image_error)): ?>
                    <div class="text-danger"><?= $image_error ?></div>
                <?php endif; ?>
            </div>
            <button type="submit" class="btn btn-success">Atualizar</button>
        </form>
    </div>
</div>
