<?php require __DIR__ . '/../navbar.phtml' ?>

<h1 class="text-center fs-2 title">Gerenciar Administradores</h1>

<div class="container mt-5">

    <a class="btn btn-success mb-2" href="<?= route('admins.create') ?>">Criar</a>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th></th>
                    <th>Email</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($admins as $admin) : ?>
                    <tr>
                        <td><img src="<?= $admin->profileImage()->path() ?>" alt="profileImage" class="profileImage"></td>
                        <td><?= $admin->email ?></td>
                        <td>
                            <div class="d-flex flex-row">
                                <a href="<?= route('admins.edit', ['id' => $admin->id]) ?>" class='btn btn-warning btn-sm mx-2'>
                                    <i class='bi bi-pencil-square'></i> Editar
                                </a>
                                <form action="<?= route('admins.destroy', ['id' => $admin->id]) ?>" method="POST" class="m-0">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class='btn btn-danger btn-sm'>
                                        <i class='bi bi-trash'></i> Excluir
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php $paginator->renderPagesNavigation(); ?>
</div>